# Generated by Django 4.0.4 on 2022-05-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('semester', models.IntegerField()),
                ('active', models.BooleanField()),
                ('staff', models.BooleanField()),
                ('admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
