# Generated by Django 4.0.4 on 2022-05-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_student_managers_alter_student_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
